---
Name: silvershop-discounts
---
LeftAndMain:
  extra_requirements_css:
    - silvershop-discounts/css/OrderCouponAdmin.css
Product:
  extensions:
    - ProductDiscountExtension
ProductVariation:
  extensions:
    - ProductVariationDiscountExtension
Order:
  extensions:
    - DiscountedOrderExtension
Product_OrderItem:
  extensions:
    - DiscountedOrderItem
#Discount:
#  constraints:
#    - ZonesDiscountConstraint
#    - CategoriesDiscountConstraint
#    - ProductsDiscountConstraint
#    - GroupDiscountConstraint
#    - MembershipDiscountConstraint
#    - DatetimeDiscountConstraint
#    - ValueDiscountConstraint
#    - UseLimitDiscountConstraint
#    - CodeDiscountConstraint
